#
# Copyright 2021 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

amqp-host=${remote.amqp.broker}
amqp-port=443

amqp-username=${amqp.user}
amqp-password=${amqp.password}
amqp-use-ssl=true
mp.messaging.connector.smallrye-amqp.wildfly.elytron.ssl.context=amqp-ssl-test

mp.messaging.outgoing.source.connector=smallrye-amqp

mp.messaging.incoming.in.connector=smallrye-amqp
mp.messaging.incoming.in.address=source
