name: Intersmash Applications - Simple build workflow


on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  simple-build-wildfly:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run:  mvn -version ; mvn clean install

  simple-build-eap-xp6:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run:  mvn -version ; mvn clean install -Pbuild-distribution.eapxp,build-stream.eapxp6
